### ISSUE TITLE
cannot run the evaluation code

### ISSUE THREAD

**Issue by leao1995** [hjkuijf/wmhchallenge#1]
https://github.com/hjkuijf/wmhchallenge/blob/10391cb1a837e913d81ed4899eef6cff88179f27/evaluation.py#L164
name 'lTest' is not defined

https://github.com/hjkuijf/wmhchallenge/blob/master/evaluation.py#L122
TypeError: in method 'Image_TransformIndexToPhysicalPoint', argument 2 of type 'std::vector< int64_t,std::allocator< int64_t > > const &'

I'm uisng python3.6 and SimpleITK3.0.11.

Thanks.

**Comment by hjkuijf** [comment]
Thanks for reporting this issue. I have fixed this and lTest is now defined on line 161: https://github.com/hjkuijf/wmhchallenge/blob/8d725b733ce56a358a5df5cd7b962b1677ea0c78/evaluation.py#L161

**Comment by NirDiamant** [comment]
Hi hjkuijf,
I have the very exact problem even after you fix

**Comment by hjkuijf** [comment]
Can you download a fresh copy of the evaluation.py file from github and give it another try? As far as I can see, it should work properly. If not, can you share the exact error message?

**Comment by NirDiamant** [comment]
Traceback (most recent call last):
  File "/home/nir/h_python1/evaluation.py", line 199, in <module>
    do()
  File "/home/nir/h_python1/evaluation.py", line 26, in do
    h95 = getHausdorff(testImage, resultImage)
  File "/home/nir/h_python1/evaluation.py", line 124, in getHausdorff
    np.transpose(np.flipud(np.nonzero(hTestArray))).astype(int))
  File "/opt/anaconda/envs/nir-gpu/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 132, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
  File "/opt/anaconda/envs/nir-gpu/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 3815, in TransformIndexToPhysicalPoint
    return _SimpleITK.Image_TransformIndexToPhysicalPoint(self, index)
TypeError: in method 'Image_TransformIndexToPhysicalPoint', argument 2 of type 'std::vector< int64_t,std::allocator< int64_t > > const &'

**Comment by hjkuijf** [comment]
That is a different kind of error. Please use python 2.7 for this script. If the error remains, you can open a new issue.
