### ISSUE TITLE
dockerize a matlab code in more details!

### ISSUE THREAD

**Issue by elahia** [hjkuijf/wmhchallenge#2]
Hi hjkuijf,

Thanks for your useful tutorial, actually i'm new in docker and i have to dockerize my matlab source code! from your page i tried to make a standalone version of my code, now i want to create the docker file! but i confused a bit!

first, I create my standalone on win10 64bit by matlab2017a, and I want to run docker on ubuntu 14.04

so i changed the first row of docker file as follows:

`

FROM **ubuntu14.04**
RUN **apt-get**  update -y \
 && **apt-get** install wget unzip libXext libXt-devel libXmu -y \
 && mkdir /mcr-install \
 && cd /mcr-install \
 && wget -nv http://www.mathworks.com/supportfiles/downloads/R2017a/deployment_files/R2017a/installers/glnxa64/MCR_R2017a_glnxa64_installer.zip \
 && unzip MCR_R2017a_glnxa64_installer.zip \
 && ./install -mode silent -agreeToLicense yes \
 && rm -Rf /mcr-install

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/MATLAB/MATLAB_Runtime/v901/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v901/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v901/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v901/sys/java/jre/glnxa64/jre/lib/amd64/native_threads:/usr/local/MATLAB/MATLAB_Runtime/v901/sys/java/jre/glnxa64/jre/lib/amd64/server:/usr/local/MATLAB/MATLAB_Runtime/v901/sys/java/jre/glnxa64/jre/lib/amd64
ENV XAPPLRESDIR=/usr/local/MATLAB/MATLAB_Runtime/v901/X11/app-defaults
ENV MCR_CACHE_VERBOSE=true
ENV MCR_CACHE_ROOT=/tmp

ADD matlab/example/for_redistribution_files_only /wmhseg_example
RUN ["chmod", "+x", "/wmhseg_example/example"]

`

so am i correct?

and is it possible to make some comment on each line of dockerfile! i know it takes time but for beginners it really helps to be more clear what is going on! 
for example  Where is "LD_LIBRARY_PATH"? or Other ENV variables! 

or how we can find our suit supportfiles in mathworks!

Sorry i know my questions are really simple, but i just start to learn docker!

Best regards,
Elahe,

**Comment by hjkuijf** [comment]
You can find more detailed instructions on the challenge website: http://wmh.isi.uu.nl/methods/example-matlab/ .

**Comment by elahia** [comment]
thanks for your reply,

but now i installed matlab on my ubuntu14,04

regards to this does any thing change?
